[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.6"
rust-crypto = "^0.2"
bincode = "1.3"
chrono = "0.4"
serde = {version = "1.0", features = ["derive"] }
hex = "0.4"